/**
 * @license
 * Copyright 2025 BrowserOS
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

import { z } from 'zod'

export type ConfigSection = 'safe' | 'dangerous'
export type ConfigGroup = 'Timeouts' | 'Limits' | 'Retention'
export type ConfigUnit = 'ms' | 'turns' | 'tokens' | 'chars' | 'lines' | 'days'

export interface ConfigKeyMeta {
  key: string
  label: string
  group: ConfigGroup
  section: ConfigSection
  unit: ConfigUnit
  min: number
  max: number
  default: number
  description: string
  risk?: string
  envVar: string
}

export const CONFIG_KEYS: ConfigKeyMeta[] = [
  {
    key: 'TIMEOUTS.TOOL_CALL',
    label: 'Tool Call Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: Number.MAX_SAFE_INTEGER,
    default: 120_000,
    description: 'Maximum time for a single tool call execution',
    envVar: 'BROWSEROS_TIMEOUT_TOOL_CALL',
  },
  {
    key: 'TIMEOUTS.TOOL_POST_ACTION',
    label: 'Tool Post-Action Delay',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 0,
    max: 30_000,
    default: 2_000,
    description: 'Delay after tool action before proceeding',
    envVar: 'BROWSEROS_TIMEOUT_TOOL_POST_ACTION',
  },
  {
    key: 'TIMEOUTS.TEST_PROVIDER',
    label: 'Test Provider Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 15_000,
    description: 'Timeout when testing LLM provider connection',
    envVar: 'BROWSEROS_TIMEOUT_TEST_PROVIDER',
  },
  {
    key: 'TIMEOUTS.REFINE_PROMPT',
    label: 'Refine Prompt Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 30_000,
    description: 'Timeout for prompt refinement requests',
    envVar: 'BROWSEROS_TIMEOUT_REFINE_PROMPT',
  },
  {
    key: 'TIMEOUTS.MCP_DEFAULT',
    label: 'MCP Default Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 60_000,
    default: 5_000,
    description: 'Default timeout for MCP operations',
    envVar: 'BROWSEROS_TIMEOUT_MCP_DEFAULT',
  },
  {
    key: 'TIMEOUTS.MCP_TRANSPORT_PROBE',
    label: 'MCP Transport Probe',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 30_000,
    default: 5_000,
    description: 'Timeout for probing MCP transport',
    envVar: 'BROWSEROS_TIMEOUT_MCP_TRANSPORT_PROBE',
  },
  {
    key: 'TIMEOUTS.MCP_CLIENT_CONNECT',
    label: 'MCP Client Connect',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 15_000,
    description: 'Timeout for MCP client connection',
    envVar: 'BROWSEROS_TIMEOUT_MCP_CLIENT_CONNECT',
  },
  {
    key: 'TIMEOUTS.CDP_CONNECT',
    label: 'CDP Connect',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 60_000,
    default: 10_000,
    description: 'Timeout for Chrome DevTools Protocol connection',
    envVar: 'BROWSEROS_TIMEOUT_CDP_CONNECT',
  },
  {
    key: 'TIMEOUTS.CDP_REQUEST_TIMEOUT',
    label: 'CDP Request Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 300_000,
    default: 60_000,
    description: 'Timeout for individual CDP requests',
    envVar: 'BROWSEROS_TIMEOUT_CDP_REQUEST_TIMEOUT',
  },
  {
    key: 'TIMEOUTS.KLAVIS_FETCH',
    label: 'Klavis Fetch Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 30_000,
    description: 'Timeout for Klavis API fetches',
    envVar: 'BROWSEROS_TIMEOUT_KLAVIS_FETCH',
  },
  {
    key: 'TIMEOUTS.SKILLS_FETCH',
    label: 'Skills Fetch Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 15_000,
    description: 'Timeout for fetching skills',
    envVar: 'BROWSEROS_TIMEOUT_SKILLS_FETCH',
  },
  {
    key: 'TIMEOUTS.SKILLS_SYNC_INTERVAL',
    label: 'Skills Sync Interval',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 60_000,
    max: 86_400_000,
    default: 2_700_000,
    description: 'Interval between skill synchronization checks (45 min)',
    envVar: 'BROWSEROS_TIMEOUT_SKILLS_SYNC_INTERVAL',
  },
  {
    key: 'TIMEOUTS.NAVIGATION',
    label: 'Navigation Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 10_000,
    description: 'Timeout for page navigation',
    envVar: 'BROWSEROS_TIMEOUT_NAVIGATION',
  },
  {
    key: 'TIMEOUTS.PAGE_LOAD_WAIT',
    label: 'Page Load Wait',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 30_000,
    description: 'Maximum wait for page load completion',
    envVar: 'BROWSEROS_TIMEOUT_PAGE_LOAD_WAIT',
  },
  {
    key: 'TIMEOUTS.STABLE_DOM',
    label: 'Stable DOM Wait',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 100,
    max: 30_000,
    default: 3_000,
    description: 'Wait time for DOM to stabilize',
    envVar: 'BROWSEROS_TIMEOUT_STABLE_DOM',
  },
  {
    key: 'TIMEOUTS.FILE_CHOOSER',
    label: 'File Chooser Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 100,
    max: 30_000,
    default: 3_000,
    description: 'Timeout for file chooser dialog',
    envVar: 'BROWSEROS_TIMEOUT_FILE_CHOOSER',
  },
  {
    key: 'TIMEOUTS.OAUTH_FLOW_TTL',
    label: 'OAuth Flow TTL',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 10_000,
    max: 3_600_000,
    default: 300_000,
    description: 'Time-to-live for OAuth flow state',
    envVar: 'BROWSEROS_TIMEOUT_OAUTH_FLOW_TTL',
  },
  {
    key: 'TIMEOUTS.OAUTH_POLL_TIMEOUT',
    label: 'OAuth Poll Timeout',
    group: 'Timeouts',
    section: 'safe',
    unit: 'ms',
    min: 10_000,
    max: 3_600_000,
    default: 300_000,
    description: 'Timeout for OAuth polling',
    envVar: 'BROWSEROS_TIMEOUT_OAUTH_POLL_TIMEOUT',
  },
  {
    key: 'TIMEOUTS.CDP_CONNECT_RETRY_DELAY',
    label: 'CDP Connect Retry Delay',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 100,
    max: 30_000,
    default: 1_000,
    description: 'Delay between CDP connection retries',
    risk: 'Too low → retry storms. Too high → slow recovery from disconnects.',
    envVar: 'BROWSEROS_TIMEOUT_CDP_CONNECT_RETRY_DELAY',
  },
  {
    key: 'TIMEOUTS.CDP_RECONNECT_DELAY',
    label: 'CDP Reconnect Delay',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 100,
    max: 60_000,
    default: 5_000,
    description: 'Delay before reconnecting to the browser',
    risk: 'Too low → rapid retry loop.',
    envVar: 'BROWSEROS_TIMEOUT_CDP_RECONNECT_DELAY',
  },
  {
    key: 'TIMEOUTS.CDP_KEEPALIVE_INTERVAL',
    label: 'CDP Keepalive Interval',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 1_000,
    max: 300_000,
    default: 30_000,
    description: 'How often to ping the browser',
    risk: 'Too low → unnecessary load. Too high → missed disconnects.',
    envVar: 'BROWSEROS_TIMEOUT_CDP_KEEPALIVE_INTERVAL',
  },
  {
    key: 'TIMEOUTS.CDP_KEEPALIVE_TIMEOUT',
    label: 'CDP Keepalive Timeout',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 1_000,
    max: 120_000,
    default: 10_000,
    description: 'Wait time for keepalive response',
    risk: 'Too low → false disconnects.',
    envVar: 'BROWSEROS_TIMEOUT_CDP_KEEPALIVE_TIMEOUT',
  },
  {
    key: 'TIMEOUTS.PAGE_LOAD_POLL_INTERVAL',
    label: 'Page Load Poll Interval',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 10,
    max: 5_000,
    default: 150,
    description: 'Polling frequency for page load detection',
    risk: 'Too low → CPU waste. Too high → slow detection.',
    envVar: 'BROWSEROS_TIMEOUT_PAGE_LOAD_POLL_INTERVAL',
  },
  {
    key: 'TIMEOUTS.OAUTH_TOKEN_EXPIRY_BUFFER',
    label: 'OAuth Token Expiry Buffer',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 10_000,
    max: 3_600_000,
    default: 300_000,
    description: 'How far before expiry to refresh tokens',
    risk: 'Too low → token expires mid-flow.',
    envVar: 'BROWSEROS_TIMEOUT_OAUTH_TOKEN_EXPIRY_BUFFER',
  },
  {
    key: 'TIMEOUTS.OAUTH_POLL_INTERVAL',
    label: 'OAuth Poll Interval',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 100,
    max: 30_000,
    default: 2_000,
    description: 'Polling frequency during OAuth flows',
    risk: 'Too low → API rate limits.',
    envVar: 'BROWSEROS_TIMEOUT_OAUTH_POLL_INTERVAL',
  },
  {
    key: 'TIMEOUTS.DEVICE_CODE_POLL_SAFETY_MARGIN',
    label: 'Device Code Poll Safety Margin',
    group: 'Timeouts',
    section: 'dangerous',
    unit: 'ms',
    min: 100,
    max: 30_000,
    default: 3_000,
    description: 'Safety margin before device code expiry',
    risk: 'Too low → flow fails prematurely.',
    envVar: 'BROWSEROS_TIMEOUT_DEVICE_CODE_POLL_SAFETY_MARGIN',
  },
  {
    key: 'AGENT_LIMITS.MAX_TURNS',
    label: 'Max Turns',
    group: 'Limits',
    section: 'safe',
    unit: 'turns',
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    default: 100,
    description: 'Maximum agent turns per conversation',
    envVar: 'BROWSEROS_LIMIT_MAX_TURNS',
  },
  {
    key: 'AGENT_LIMITS.DEFAULT_CONTEXT_WINDOW',
    label: 'Default Context Window',
    group: 'Limits',
    section: 'safe',
    unit: 'tokens',
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    default: 200_000,
    description: 'Default context window size for LLM',
    envVar: 'BROWSEROS_LIMIT_DEFAULT_CONTEXT_WINDOW',
  },
  {
    key: 'TOOL_LIMITS.INLINE_PAGE_CONTENT_MAX_CHARS',
    label: 'Inline Page Content Limit',
    group: 'Limits',
    section: 'safe',
    unit: 'chars',
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    default: 5_000,
    description: 'Maximum inline page content characters',
    envVar: 'BROWSEROS_LIMIT_INLINE_PAGE_CONTENT_MAX_CHARS',
  },
  {
    key: 'TOOL_LIMITS.FILESYSTEM_READ_MAX_LINES',
    label: 'Filesystem Read Max Lines',
    group: 'Limits',
    section: 'safe',
    unit: 'lines',
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    default: 500,
    description: 'Maximum lines when reading files',
    envVar: 'BROWSEROS_LIMIT_FILESYSTEM_READ_MAX_LINES',
  },
  {
    key: 'TOOL_LIMITS.FILESYSTEM_READ_MAX_CHARS',
    label: 'Filesystem Read Max Chars',
    group: 'Limits',
    section: 'safe',
    unit: 'chars',
    min: 1,
    max: Number.MAX_SAFE_INTEGER,
    default: 15_000,
    description: 'Maximum characters when reading files',
    envVar: 'BROWSEROS_LIMIT_FILESYSTEM_READ_MAX_CHARS',
  },
  {
    key: 'AGENT_LIMITS.COMPACTION_SUMMARIZATION_TIMEOUT_MS',
    label: 'Compaction Summarization Timeout',
    group: 'Limits',
    section: 'dangerous',
    unit: 'ms',
    min: 5_000,
    max: 600_000,
    default: 60_000,
    description: 'Timeout for LLM summarization during compaction',
    risk: 'Too low → incomplete summaries during compaction.',
    envVar: 'BROWSEROS_TIMEOUT_COMPACTION_SUMMARIZATION',
  },
  {
    key: 'AGENT_LIMITS.COMPACTION_MAX_SUMMARIZATION_INPUT',
    label: 'Compaction Max Input',
    group: 'Limits',
    section: 'dangerous',
    unit: 'tokens',
    min: 1_000,
    max: 1_000_000,
    default: 100_000,
    description: 'Max input tokens for compaction summarization',
    risk: 'Too low → context loss. Too high → API costs.',
    envVar: 'BROWSEROS_LIMIT_COMPACTION_MAX_SUMMARIZATION_INPUT',
  },
  {
    key: 'AGENT_LIMITS.COMPACTION_TOOL_OUTPUT_MAX_CHARS',
    label: 'Compaction Tool Output Limit',
    group: 'Limits',
    section: 'dangerous',
    unit: 'chars',
    min: 100,
    max: 1_000_000,
    default: 15_000,
    description: 'Max chars kept from tool outputs in transcript',
    risk: 'Too low → lost context. Too high → memory bloat.',
    envVar: 'BROWSEROS_LIMIT_COMPACTION_TOOL_OUTPUT_MAX_CHARS',
  },
  {
    key: 'PATHS.SOUL_MAX_LINES',
    label: 'Soul Max Lines',
    group: 'Retention',
    section: 'safe',
    unit: 'lines',
    min: 10,
    max: 10_000,
    default: 150,
    description: 'Maximum lines in SOUL.md',
    envVar: 'BROWSEROS_LIMIT_SOUL_MAX_LINES',
  },
  {
    key: 'PATHS.MEMORY_RETENTION_DAYS',
    label: 'Memory Retention',
    group: 'Retention',
    section: 'safe',
    unit: 'days',
    min: 1,
    max: 365,
    default: 30,
    description: 'Days to retain memory entries',
    envVar: 'BROWSEROS_LIMIT_MEMORY_RETENTION_DAYS',
  },
  {
    key: 'PATHS.SESSION_RETENTION_DAYS',
    label: 'Session Retention',
    group: 'Retention',
    section: 'safe',
    unit: 'days',
    min: 1,
    max: 365,
    default: 30,
    description: 'Days to retain session data',
    envVar: 'BROWSEROS_LIMIT_SESSION_RETENTION_DAYS',
  },
]

export const CONFIG_KEY_MAP = new Map(
  CONFIG_KEYS.map((configKey) => [configKey.key, configKey] as const),
)

const ConfigValueSchema = z
  .number()
  .int('Must be an integer')
  .nonnegative('Must be non-negative')
  .refine(Number.isSafeInteger, 'Must be a safe integer')

export const ConfigOverridesSchema = z.record(z.string(), ConfigValueSchema)

export type ConfigOverrides = z.infer<typeof ConfigOverridesSchema>

export function validateConfigValue(key: string, value: number): string | null {
  const meta = CONFIG_KEY_MAP.get(key)
  if (!meta) return `Unknown config key: ${key}`
  if (!Number.isSafeInteger(value)) return 'Must be a safe integer'
  if (value < 0) return 'Must be non-negative'
  if (value < meta.min) return `Value ${value} is below minimum ${meta.min}`
  if (value > meta.max) return `Value ${value} exceeds maximum ${meta.max}`
  return null
}

export function validateAllOverrides(
  overrides: ConfigOverrides,
): Map<string, string> {
  const errors = new Map<string, string>()

  for (const [key, value] of Object.entries(overrides)) {
    const error = validateConfigValue(key, value)
    if (error) errors.set(key, error)
  }

  return errors
}
